            int sayi1,sayi2,sonuc;
            Console.Write("1.Sayıyı Giriniz : ");
            sayi1=Convert.ToInt32(Console.ReadLine());
            Console.Write("2.Sayıyı Giriniz : ");
            sayi2=Convert.ToInt32(Console.ReadLine());
            sonuc=sayi1+sayi2;
            Console.WriteLine("{0} + {1} = {2}",sayi1,sayi2,sonuc);
            sonuc=sayi1-sayi2;
            Console.WriteLine("{0} - {1} = {2}",sayi1,sayi2,sonuc);
            sonuc=sayi1*sayi2;
            Console.WriteLine("{0} * {1} = {2}",sayi1,sayi2,sonuc);
            sonuc=sayi1/sayi2;
            Console.WriteLine("{0} / {1} = {2}",sayi1,sayi2,sonuc);